from typing import Annotated, Any, Dict, List, Optional
from pydantic import BaseModel, Field
from langgraph.graph.message import add_messages

class CustomerProfile(BaseModel):
    customer_id: str = Field(..., description="Unique identifier for the customer")
    name: str = Field(..., description="Full name of the customer") 
    contact_info: Dict[str, Any] = Field(
        default_factory=dict, 
        description="Contact details (e.g., email, phone, preferred_channel)"
    )
    purchase_history: List[Dict[str, Any]] = Field(
        default_factory=list, 
        description="List of purchases, each with item_id, timestamp, and amount"
    )
    total_spend: float = Field(0.0, description="Total monetary amount spent by the customer")
    last_purchase_date: Optional[str] = Field(None, description="Date of the last purchase")
    notes: Optional[str] = Field(None, description="Qualitative notes or preferences for this customer")


class InventoryItem(BaseModel):
    """Pydantic model representing an item in the inventory, managed by the Stock Agent."""
    sku: str = Field(..., description="Stock Keeping Unit, unique identifier")
    product_name: str = Field(..., description="Name of the product")
    category: str = Field(..., description="Product category")
    stock_quantity: int = Field(..., description="Current quantity in stock")
    price: float = Field(..., description="Price of a single unit")
    reorder_point: int = Field(..., description="Threshold level to trigger restock flags")
    days_in_stock_unsold: int = Field(..., description="Number of days the item has remained unsold (slow-moving flag)")


class TrackedLead(BaseModel):
    lead_id: str = Field(..., description="Unique identifier for the lead")
    source: str = Field(..., description="Lead source, e.g., Web Form, Cold Search")
    company_name: Optional[str] = Field(None, description="Name of the company/organization")
    contact_name: Optional[str] = Field(None, description="Name of the contact person")
    estimated_deal_size: float = Field(0.0, description="Estimated deal value/size")
    lead_score: float = Field(0.0, description="Lead score calculated by the scoring agent")
    status: str = Field("New", description="Status of the lead, e.g., New, Contacted, Nurturing, Qualified")
    next_action: Optional[str] = Field(None, description="Next step action item, e.g., Draft outreach message")


class ActiveCampaign(BaseModel):
    campaign_id: str = Field(..., description="Unique identifier for the campaign")
    title: str = Field(..., description="Title or name of the campaign")
    target_segment: str = Field(..., description="Reference to target customer list or criteria")
    marketing_channels: List[str] = Field(default_factory=list, description="Channels used, e.g., WhatsApp, Email")
    generated_content: Dict[str, Any] = Field(default_factory=dict, description="Generated content/templates per channel")
    status: str = Field("Draft", description="Status of the campaign, e.g., Draft, Pending Approval, Sent")
    budget: float = Field(0.0, description="Budget allocated for the campaign")
    estimated_roi: Optional[float] = Field(None, description="Estimated Return on Investment")
    conversion_count: Optional[int] = Field(None, description="Count of conversions generated by the campaign")

# appending campaigns
def append_campaigns(left: Optional[List[ActiveCampaign]], right: Optional[List[ActiveCampaign]]) -> List[ActiveCampaign]:
    if left is None:
        left = []
    if right is None:
        right = []
    return left + right


class SMEState(Dict[str, Any]):
    # chat history 
    messages: Annotated[list, add_messages]
    
    # customer profiles
    customer_profiles: List[CustomerProfile]
    # inventory items
    current_inventory: List[InventoryItem]
    # tracked leads
    tracked_leads: List[TrackedLead]   
    # marketing campaigns
    active_campaigns: Annotated[List[ActiveCampaign], append_campaigns]
    # next agents
    next_agents: List[str]